name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1                     # AWS region (e.g., us-west-1)
  ECR_REPOSITORY: nestjs-server-demo         # ECR repository name
  ECS_SERVICE: nestjs-server-demo-service   # ECS service name
  ECS_CLUSTER: nestjs-server-demo-cluster   # ECS cluster name
  ECS_TASK_DEFINITION: nestjs-server-demo-task # ECS task definition family name (not file path)
  CONTAINER_NAME: nestjs-server-demo-container # Container name in ECS task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials for deployment
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@0e613a0980cbf65ed5b322eb7a1e075d28913a83
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Step 3: Verify AWS credentials and account identity
      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity

      # Step 4: Login to Amazon ECR Public
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
        with:
          registry: ${{ secrets.ECR_REGISTRY }}  # Use the ECR Public registry URL here

      # Step 5: Build, tag, and push the Docker image to Amazon ECR Public
      - name: Build, tag, and push image to Amazon ECR Public
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}  # ECR Public registry URL
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker image and push it to ECR Public
          aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # Step 6: Download the current ECS task definition
      - name: Download ECS task definition
        id: download-task-def
        run: |
          # Download the current ECS task definition as JSON
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            --region ${{ env.AWS_REGION }} --query taskDefinition > task-definition.json
        continue-on-error: true

      # Step 7: Check if the task definition was downloaded successfully
      - name: Check task definition download
        run: |
          if [ ! -f task-definition.json ]; then
            echo "ECS task definition not found, aborting deployment!";
            exit 1;
          fi

      # Step 8: Update ECS task definition with the new Docker image
      - name: Update ECS task definition with new image
        id: update-task-def
        run: |
          # Fix the typo and correctly update the container image in the task definition
          jq '.containerDefinitions[0].image="${{ steps.build-image.outputs.image }}"' task-definition.json > updated-task-definition.json
          mv updated-task-definition.json task-definition.json

      # Step 9: Deploy the updated task definition to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@df9643053eda01f169e64a0e60233aacca83799a
        with:
          task-definition: task-definition.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      # Step 10: Force redeploy if needed
      - name: Force redeploy
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --region ${{ env.AWS_REGION }} --force-new-deployment
