name: Deploy to ECS

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'
      ECR_REPOSITORY: 'my-ecr-repo'
      ECS_CLUSTER: 'my-ecs-cluster'
      ECS_SERVICE: 'my-ecs-service'
      ECS_TASK_DEFINITION: 'my-task-definition'
      IMAGE_TAG: ${{ github.sha }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.AWS_REGION }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .

      - name: Tag Docker image for ECR
        run: |
          docker tag ${{ env.ECR_REPOSITORY }}:$IMAGE_TAG ${{ secrets.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Fetch current ECS task definition
        id: fetch_task_definition
        run: |
          task_definition=$(aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            --region ${{ env.AWS_REGION }} \
            --query "taskDefinition" \
            --output json)
          
          echo "task_definition=$task_definition" >> $GITHUB_ENV

      - name: Register new ECS task definition
        id: register_task_definition
        run: |
          new_task_definition=$(echo ${{ env.task_definition }} | jq '.containerDefinitions[0].image = "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"' )

          # Register new task definition with updated image
          new_task_definition_arn=$(aws ecs register-task-definition \
            --family ${{ env.ECS_TASK_DEFINITION }} \
            --container-definitions "$new_task_definition" \
            --region ${{ env.AWS_REGION }} \
            --query "taskDefinition.taskDefinitionArn" \
            --output text)

          echo "New Task Definition ARN: $new_task_definition_arn"
          echo "new_task_definition_arn=$new_task_definition_arn" >> $GITHUB_ENV

      - name: Deploy to ECS Service
        run: |
          # Deploy the new task definition
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER }} \
            --service ${{ env.ECS_SERVICE }} \
            --task-definition ${{ env.new_task_definition_arn }} \
            --region ${{ env.AWS_REGION }}
